name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 7 * * *'  # runs every day at 07:15 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit by 23f1001828@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
