name: Daily Commit Workflow

on:
  schedule:
    # Runs daily at 07:15 UTC (adjust if needed)
    - cron: '15 7 * * *'
  workflow_dispatch:  # allows manual trigger too

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add timestamp and commit (23f1001828@ds.study.iitm.ac.in)
        run: |
          echo "Daily commit at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily commit: $(date -u)"
          git push
